# Generated by Django 4.2.14 on 2024-07-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEORobotapp', '0002_alter_category_id_alter_page_id_alter_seometadata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.CharField(default='default content', max_length=300),
            preserve_default=False,
        ),
    ]
